{% set name = "resfinder" %}
<<<<<<< HEAD
{% set version = "master" %}
=======
{% set version = "4.0" %}
>>>>>>> 19f078d7392961ed4cee2261bbb96b5fb3951aa1

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  skip: True # [osx]
  number: 0

source:
  fn: {{ name|lower }}-{{ version }}.tar.gz
  url: https://bitbucket.org/genomicepidemiology/{{ name|lower }}/get/{{ version }}.tar.gz
<<<<<<< HEAD
  sha256: e00bb1e2c2bdf2121e1c3e6837ce023087224280d7c737c14f28ece6d80123d2
  patches:
    - INSTALL_DB.patch
    - UPDATE_DB.patch

requirements:
  build:
  - perl-app-cpanminus
=======
  sha256: eecb3b11edda912c70a17de9e56cce78f7ba5f67f84ad86b83d2bbffa40c730b

requirements:
  build:
>>>>>>> 19f078d7392961ed4cee2261bbb96b5fb3951aa1
  - perl-bioperl
  - perl-data-dumper
  - perl-getopt-long
  - perl-file-temp

  run:
  - blast
<<<<<<< HEAD
  - perl-app-cpanminus
=======
>>>>>>> 19f078d7392961ed4cee2261bbb96b5fb3951aa1
  - perl-bioperl
  - perl-data-dumper
  - perl-getopt-long
  - perl-file-temp
  
test:
  commands:
    - 

about:
  home: https://bitbucket.org/genomicepidemiology/resfinder
  license: 
  license_file: 
  summary: ResFinder identifies acquired antimicrobial resistance genes and/or find chromosomal mutations in total or partial sequenced isolates of bacteria.

