{% set name = "MiCall-Lite" %}
{% set version = "0.1rc2" %}
{% set sha256 = "aa01a8f08f05b221d2518f89c56783cc3b6e6d15dd85f0cd6aaa319c2f978ffb" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
  url: https://github.com/PoonLab/{{ name }}/archive/Lite-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: "$PYTHON setup.py install"
  
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
  run:
    - python
    - python-levenshtein
    - bowtie2

test:
  commandss:
      - micall -h

about:
    home: https://github.com/PoonLab/MiCall-Lite
    license: GNU Affero General Public License v3.0
    license_file: LICENSE.txt
    summary: |
      A bioinformatic pipeline for mapping FASTQ data to a set of reference
      sequences to generate consensus sequences, variant calls and coverage maps.
