{% set name = "grapetree" %}
{% set version = "2.1" %}
{% set sha256 = "b68985a2bdbe8353f9657ce3bd5b42be67c3c28e972d6fa390d12a0f19ff8b74" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: '0'
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  
requirements:
  host:
    - python
    - pip
  run:
    - click
    - decorator
    - flask
    - itsdangerous
    - jinja2
    - markupsafe
    - networkx
    - numpy
    - psutil
    - werkzeug
    - numba
    - ete3

test:
    commands:
        - grapetree -h

about:
    home: https://github.com/achtman-lab/GrapeTree
    license: GPL-3.0
    license_file: LICENSE
    summary: A fully interactive tree visualization program, which supports facile manipulations of both tree layout and metadata.
